/*
   Step 2: RFM Metrics Calculation
   Objective: Calculate Recency, Frequency, and Monetary values for each customer.
   
   Metrics Definition:
   - Recency: Days since last purchase (relative to the dataset's max date + 1 day).
   - Frequency: Count of unique invoices (transactions).
   - Monetary: Total revenue generated by the customer.
   
   Scoring Logic:
   - We use NTILE(5) to divide customers into 5 equal groups (quintiles).
   - Score 5 is the highest (Best), Score 1 is the lowest (Worst).
*/

DROP TABLE IF EXISTS rfm_metrics;

CREATE TABLE rfm_metrics AS
WITH reference_date AS (
    -- Establish a reference point for Recency calculation
    SELECT DATE(MAX(invoice_date), '+1 day') AS max_date 
    FROM clean_transactions
),
customer_agg AS (
    -- Aggregate transaction data by Customer ID
    SELECT
        t.customer_id,
        (SELECT max_date FROM reference_date) AS ref_d,
        MAX(t.invoice_date) AS last_purchase_date,
        COUNT(DISTINCT t.invoice) AS frequency,
        SUM(t.total_amount) AS monetary
    FROM clean_transactions t
    GROUP BY t.customer_id
)
SELECT
    customer_id,
    CAST(julianday(ref_d) - julianday(last_purchase_date) AS INTEGER) AS recency,
    frequency,
    monetary,
    -- Assign scores from 1 to 5
    NTILE(5) OVER (ORDER BY CAST(julianday(ref_d) - julianday(last_purchase_date) AS INTEGER) DESC) AS r_score,
    NTILE(5) OVER (ORDER BY frequency ASC) AS f_score,
    NTILE(5) OVER (ORDER BY monetary ASC) AS m_score
FROM customer_agg;